(LOAD "C:/Users/User/Google Drive/Shen Professional/Shen/LogicLab/LKL/ffi.lsp")
(cd "C:\Users\User\Google Drive\Shen Professional\Shen\LogicLab\LKL")
(load "external.shen")
(load "syntax.shen")
(tc -)
(load "semanticsuntyped.shen")
(load "prover9untyped.shen")
(tc +)
(load "prover9typed.shen")
(load "semantics.shen")
(load "LKLrules.shen")
