
(load "Symbols/symbols1.shen")
(tc +)
(load "Symbols/symbols2.shen")
(tc -)
(factorise +)
(load "Maths/macros.shen")
(factorise -)
(tc +)
(load "Maths/maths.shen")
(tc -)
(load "Maths/rationals.dtype")
(tc +)
(load "Maths/rationals.shen")
(tc -)
(load "Maths/complex.dtype")
(tc +)
(load "Maths/complex.shen")
(tc -)
(load "Maths/numerals.dtype")
(tc +)
(load "Maths/numerals.shen")
(load "Lists/lists.shen")
(load "Strings/macros.shen")
(load "Strings/strings.shen")
(tc -)
(load "Strings/smart.shen")
(factorise +)
(load "Vectors/macros.shen")
(factorise -)
(tc +)
(load "IO/prettyprint.shen")
(tc -)
(load "IO/delete-file.shen")
(tc +)
(load "IO/files.shen")
(load "Tuples/tuples.shen")
(tc -)
(load "package-stlib.shen")

\\ all external functions of the standard library are declared as system functions
(let External  (external stlib)
     ExternalF (filter (/. X (> (arity X) -1)) External)
     Systemf   (map (fn systemf) ExternalF)
     ok)

(preclude-all-but [])
(set shen.*userdefs* [])
(cd "")
(tc -)
