(tc -)

\\ StLib is now included, this is not necessary
\\(cd "lib")
\\(if (= (language) "Scheme") (load "patches-scheme.shen") skip)

\\(cd "lib/stlib")
\\(load "install.shen")

(if (and (package? stlib)
         (y-or-n? "install concurrency? (required for Shen/tk)"))
    (do (tc -)
        (cd "lib/concurrency")
        (load "concurrency.dtype")
        (tc +)
        (load "concurrency.shen"))
    skip)

(if (and (package? p) (y-or-n? "install Shen/tk + IDE?"))
    (do (tc -)
        (cd "lib/tk")
        (load "loadme.shen")
        (tc -)
        (cd "lib/ide")
        (load "idedec.shen")
        (tc +)
        (load "ide.shen")
        (tk.types -))
    skip)

(if (and (package? stlib) (y-or-n? "install THORN?"))
    (do (cd "lib/thorn")
        (tc -)
        (load "datatypes.shen")
        (load "THORN20.shen"))
    skip)

(if (and (package? stlib) (y-or-n? "install Logic Lab?"))
    (do (cd "lib/logic-lab")
        (tc -)
        (load "compiler.shen")
        (tc +)
        (load "gpa.shen"))
    skip)

(preclude-all-but [])
(set shen.*userdefs* [])
(cd "")
(tc -)
(if (and (= (language) "Scheme") (package? ide)) (ide.myIDE) skip)

